### ISSUE TITLE
move React to peerDependencies

### ISSUE THREAD

**Issue by petermikitsh** [fdaciuk/react-trianglify#1]
Due to my project's structure, I'm accidentally getting two copies of React installed. 

When running `npm ls react`:

```
└─┬ react-trianglify@0.1.0 invalid
  └── react@15.4.2  extraneous
```

Please declare react to be a peerDependency in `package.json`, e.g.,

```
  "peerDependencies": {
    "react": "^15.4.0"
  }
```

To prevent the second installation. Thanks!

**Comment by fdaciuk** [comment]
Hey @petermikitsh! Thanks for your suggestion :D 
I've added `react`, `react-dom` and `trianglify` as `dependency` and `peerDependency`. So, if you don't have any of this dependencies, it will be automatically installed =)

**Comment by petermikitsh** [comment]
@fdaciuk Hey! I should've been more descriptive in the original write-up. I think react and react-dom should be in `devDependencies` and `peerDependencies`, but not `dependencies`. More info in the first comment here about the differences: http://stackoverflow.com/questions/18875674/whats-the-difference-between-dependencies-devdependencies-and-peerdependencies

By putting react/react-dom into `devDependencies`, you'll get the modules installed when developing the package; and by placing react/react-dom into `peerDependencies`, you're nudging users to make sure their main project (that consumes the react-trianglify project) has an acceptable version of react/react-dom specified, but you are not explicitly installing it for them (as `dependencies` would do).

Looking at other folks who Release react modules, that seems to be the common setup. I look at the [package.json](https://github.com/callemall/material-ui/blob/master/package.json#L44-L106) file for material-ui and confirmed that react/react-dom are only included in `peerDependencies` and `devDependencies`.
