### ISSUE TITLE
[pt-BR] Tradução da documentação

### ISSUE THREAD

**Issue by fdaciuk** [fdaciuk/react-trianglify#17]
Precisamos traduzir a documentação do `react-trianglify` para Português do Brasil.

As discussões gerais desse projeto deverão ser em inglês, mas essa issue, especificamente, pode ser discutida em português, já que tem relação com a tradução da documentação para pt-BR.

Se você gostaria de trabalhar nessa issue, sinalize aqui na issue, e vamos discutindo os detalhes de como deve ser feita essa tradução, ok? :)

**Comment by eduardojansen** [comment]
@fdaciuk pode atribuir pra mim essa issue.

**Comment by fdaciuk** [comment]
Boa @eduardojansen 🙌🏾

**Comment by eduardojansen** [comment]
@fdaciuk PR enviado!

**Comment by fdaciuk** [comment]
Boa @eduardojansen! Já foi revisar :)
