### ISSUE TITLE
Move from docz to storybook

### ISSUE THREAD

**Issue by fdaciuk** [fdaciuk/react-trianglify#18]
Remove docz and add storybook for this project.

**Comment by adeonir** [comment]
@fdaciuk yo, marca aí pra mim!

**Comment by fdaciuk** [comment]
Booaa ❤️

**Comment by fdaciuk** [comment]
Fala @adeonir! Não sei se você pretende mexer nisso ainda, mas eu atualizei a lib para a versão mais recente do trianglify e React, e já removi o docz!

Então, se for mexer nisso, só precisa adicionar o storybook agora :)

Se não conseguir mexer, só me avise que eu faço isso, ok? :)

**Comment by adeonir** [comment]
Ae @fdaciuk! Cara, ainda pretendo fazer sim. Só acabei me enrolando aqui com outras coisas.

**Comment by fdaciuk** [comment]
Massa, só pra deixar alinhado mesmo :D
